#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &

bash ~/.config/polybar/scripts/pywal.sh /home/pranav/Pictures/wallpapers/ &&
bash ~/.config/custom-scripts/alacritty/generate-theme.sh &&
bash ~/.config/custom-scripts/brave/generate-theme.sh &&
bash ~/.config/polybar/launch.sh &&

bspc monitor -d I II III IV V


bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Brave-browser desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a nemo desktop='^3'

