#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
connman-gtk &
xrandr --output HDMI1 --left-of eDP1 &
$HOME/.config/polybar/launch.sh
feh --randomize --bg-fill $HOME/Pictures/wallpapers*
bspc monitor -d I II III IV V


bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


