#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
bash $HOME/.config/polybar/launch.sh
feh --randomize --bg-fill /home/pranav/Pictures/wallpapers*
#bash ${HOME}/.config/bspwm/./styli.sh -w 1366 -h 768

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V


bspc config border_width         0
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a code desktop='^8' state=floating follow=on
bspc rule -a brave desktop='^2'
bspc rule -a code state=floating desktop="^8"
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off


