#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
bash $HOME/.config/polybar/launch.sh
feh --randomize --bg-fill $HOME/Pictures/wallpapers*


#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V


bspc config border_width         0
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a code state=floating desktop="^1"
bspc rule -a firefox desktop='^2'


